### ISSUE TITLE
Validation Fail - Version not supported. 7.8.0-beta

### ISSUE THREAD

**Issue by Linkinbr** [GameAnalytics/GA-SDK-UNITY#24]
Info/GameAnalytics: Validation fail - configure sdk version: Sdk version not supported. String: unity 7.8.0-beta

I get this error while using the latest version and no events go thru.

**Comment by dorin-ga** [comment]
Hello, this is a known issue for the unity webgl plugin and we are working on releasing a patch ASAP.

Until then as a workaround you can change the validation in this file to be able to send events from WebGL: [here](https://github.com/GameAnalytics/GA-SDK-UNITY/blob/master/Runtime/WebGL/GameAnalytics.jspre#L1049)
