### ISSUE TITLE
Gameanalytics for Mac builds

### ISSUE THREAD

**Issue by boraty14** [GameAnalytics/GA-SDK-UNITY#31]
![Screenshot 2024-04-03 121547](https://github.com/GameAnalytics/GA-SDK-UNITY/assets/85781952/a113ec48-a6cc-418e-88de-a4efb00e3fca)

As shown in the picture, documentation shows it like Unity and Unreal does not support Mac environment, while other engines does. Is this the case? When I searched it up a bit I couldn't find anything in the docs but found some issue related to this in 2020

https://github.com/GameAnalytics/GA-SDK-C-SHARP/issues/44

Just wanted to clarify before using GA. Thanks

**Comment by dorin-ga** [comment]
Hello, both the Unity and Unreal SDKs do support MacOS. The documentation seems to be wrong in that regard and we will update it.
