### ISSUE TITLE
Version validation fail from unity 7.10.0-beta

### ISSUE THREAD

**Issue by vince137** [GameAnalytics/GA-SDK-UNITY#33]
Hey,

Running with the last version from master, I have the following error during the init:

`Info/GameAnalytics: Validation fail - configure sdk version: Sdk version not supported. String: unity 7.10.0-beta`

Seems like the `-beta` is not handled by the validation regex.

**Comment by dorin-ga** [comment]
Hello, on what platform is this happening?

**Comment by vince137** [comment]
> Hello, on what platform is this happening?

WindowsPlayer

**Comment by dorin-ga** [comment]
We have found the cause and will be rolling out a fix for this issue.
